server {
    server_name neochoice.ru www.neochoice.ru;
    root /var/www/neochoice.ru;
    index index.html;

    location /.well-known/acme-challenge/ { auth_basic off; root /var/www/html; }
    include /etc/nginx/snippets/auth.conf;

    location / { try_files $uri $uri/ =404; }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/neochoice.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/neochoice.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = www.neochoice.ru) { return 301 https://$host$request_uri; }
    if ($host = neochoice.ru) { return 301 https://$host$request_uri; }
    listen 80; server_name neochoice.ru www.neochoice.ru; return 404;
}
